export declare const AGENTS: {
    npm: {
        run: (args: string[]) => string;
        install: string;
        frozen: string;
        global: string;
        add: string;
        upgrade: string;
        'upgrade-interactive': null;
        execute: string;
        uninstall: string;
        global_uninstall: string;
        audit: string;
        bin: string;
        global_bin: string;
        link: string;
        list: string;
        global_list: string;
        outdated: string;
        global_outdated: string;
        publish: string;
        version: string;
        test: string;
        help: string;
        diff: string;
    };
    pnpm: {
        run: (args: string[]) => string;
        install: string;
        frozen: string;
        global: string;
        add: string;
        upgrade: string;
        'upgrade-interactive': string;
        execute: string;
        uninstall: string;
        global_uninstall: string;
        audit: string;
        bin: string;
        global_bin: string;
        link: string;
        list: string;
        global_list: string;
        outdated: string;
        global_outdated: string;
        publish: string;
        version: string;
        test: string;
        help: string;
        diff: string;
    };
    yarn: {
        run: string;
        install: string;
        frozen: string;
        global: string;
        add: string;
        upgrade: string;
        'upgrade-interactive': string;
        execute: string;
        uninstall: string;
        global_uninstall: string;
        audit: string;
        bin: string;
        global_bin: string;
        link: string;
        list: string;
        global_list: string;
        outdated: string;
        global_outdated: string;
        publish: string;
        version: string;
        test: string;
        help: string;
        diff: string;
    };
    'yarn@berry': {
        run: string;
        install: string;
        frozen: string;
        global: string;
        add: string;
        upgrade: string;
        'upgrade-interactive': string;
        execute: string;
        uninstall: string;
        global_uninstall: string;
        audit: string;
        bin: string;
        global_bin: string;
        link: string;
        list: string;
        global_list: string;
        outdated: string;
        global_outdated: string;
        publish: string;
        version: string;
        test: string;
        help: string;
        diff: string;
    };
};
export declare type Agent = (keyof typeof AGENTS) | 'prompt';
export declare type Command = keyof typeof AGENTS.npm;
export declare const agents: Agent[];
export declare const LOCKS: Record<string, Agent>;
export declare const LOCKS_PATTERN: RegExp;
export declare const INSTALL_PAGE: Record<Agent, string>;
export {}
